export const FUNCTIONS = {
    GET_EDIT_POST:'GET_EDIT_POST',
    GET_INITIAL:'GET_INITIAL',
    GET_USER:'GET_USER',
    GET_PROFILE_EMAIL:'GET_PROFILE_EMAIL',
    GET_FIRST_NAME:'GET_FIRST_NAME',
    GET_LAST_NAME:'GET_LAST_NAME',
    GET_USERNAME:'GET_USERNAME',
    GET_ID:'GET_ID',
    GET_SAMPLE_BLOG_CARDS:'GET_SAMPLE_BLOG_CARDS',
}
